
include (GNUInstallDirs)

set (SAXSVIEW_INSTALL_BINDIR ${CMAKE_INSTALL_BINDIR})
set (SAXSVIEW_INSTALL_LIBDIR ${CMAKE_INSTALL_LIBDIR})

set (SAXSVIEW_INSTALL_PYPKGDIR ${CMAKE_INSTALL_LIBDIR}/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages)

# Install the license ...
install (FILES COPYING.txt
         DESTINATION .)
